spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  profiles:
    active: test
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        
springdoc:
  paths-to-match: /products/**
  swagger-ui:
    use-root-path: true        
    
    


